# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dlnotes',
                'doc_host': 'https://thigm85.github.io',
                'git_url': 'https://github.com/thigm85/dlnotes',
                'lib_path': 'dlnotes'},
  'syms': {}}